name: Deploy to server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo" 

  second-jobs:
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo de nuevo
        run: echo "Hola mundo de nuevo"
